### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes

### method
stage: sft
do_train: true
freeze_vision_tower: false
finetuning_type: lora
lora_target: all
lora_rank: 128
lora_dropout: 0.0
deepspeed: examples/deepspeed/ds_z0_config.json
flash_attn: fa2
enable_liger_kernel: true

### dataset
dataset: pubtabnet
template: qwen2_vl
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_vl_7b/v1
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
run_name: qwen2_vl

### eval
eval_strategy: 'no'